baseURL = 'https://evgenii-petrov.net/'
languageCode = 'en-US'
title = 'blin'

[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[module]
[module.hugoVersion]
extended = false
min = '0.146.0'

[outputFormats.RSS]
baseName = "feed"
